name = "GeometryOpsCore"
uuid = "05efe853-fabf-41c8-927e-7063c8b9f013"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>", "Rafael Schouten <rafaelschouten@gmail.com>", "Skylar Gering <skygering@gmail.com>", "and contributors"]
version = "0.1.9"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataAPI = "1"
GeoInterface = "1.2"
StableTasks = "0.1.5"
Tables = "1"
julia = "1.9"
