name = "GeometryOpsTestHelpers"
uuid = "47ae2730-6264-4af1-919b-a18bc445f019"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>"]
version = "0.1.0"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"

[extensions]
GeometryOpsTestHelpersArchGDALExt = "ArchGDAL"
GeometryOpsTestHelpersGeometryBasicsExt = "GeometryBasics"
GeometryOpsTestHelpersLibGEOSExt = "LibGEOS"

[compat]
julia = "1.9"

